# Generated by Django 4.2.7 on 2026-04-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='self_harm_detected',
            field=models.BooleanField(default=False),
        ),
    ]
