# Generated by Django 4.2.7 on 2026-04-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0002_chatmessage_emotion_chatmessage_self_harm_detected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='self_harm_detected',
        ),
    ]
