# Generated by Django 4.2.7 on 2026-04-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_emotion_user_emotion_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_emotion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emotion_last_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_flagged_self_harm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_harm_flagged_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='self_harm_flagged_by',
        ),
    ]
