# Generated by Django 4.2.7 on 2026-04-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for choice type questions', null=True),
        ),
    ]
