# Generated by Django 4.2.7 on 2026-04-25 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_question_options_post_fake_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(choices=[('quit', 'Quit'), ('reduce', 'Reduce'), ('control', 'Control')], max_length=20)),
                ('short_term_goal', models.TextField(help_text='Goal to achieve in 7 days')),
                ('long_term_goal', models.TextField(help_text='Goal to achieve in 30-60 days')),
                ('hours_per_day', models.IntegerField(help_text='Hours per day dedicated to recovery activities')),
                ('activities', models.JSONField(default=list, help_text='List of activities user is willing to do')),
                ('activity_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('risk_situations', models.TextField(blank=True, help_text='Situations that make user want to use again')),
                ('risk_level', models.IntegerField(default=0, help_text='Risk level 0-100%')),
                ('ai_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehabilitation_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('completed_activities', models.BooleanField(default=False)),
                ('mood_rating', models.IntegerField(help_text='Mood rating 1-5')),
                ('craving_intensity', models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('strong', 'Strong')], default='none', max_length=20)),
                ('relapsed', models.BooleanField(default=False)),
                ('triggers', models.TextField(blank=True, help_text='What triggered cravings if any')),
                ('confidence_rating', models.IntegerField(help_text='Confidence rating 1-5')),
                ('cravings_handling', models.TextField(blank=True, help_text='How did you handle cravings today')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('ai_analysis', models.TextField(blank=True)),
                ('self_harm_detected', models.BooleanField(default=False)),
                ('self_harm_alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rehabilitation_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='core.rehabilitationplan')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('rehabilitation_plan', 'date')},
            },
        ),
    ]
