# Generated by Django 4.2.7 on 2026-04-28 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rehabilitationplan_dailyprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='druginformation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_drugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginformation',
            name='health_issues',
            field=models.TextField(blank=True, help_text='Health issues caused by this drug', null=True),
        ),
        migrations.AddField(
            model_name='druginformation',
            name='withdrawal_symptoms',
            field=models.TextField(blank=True, help_text='Withdrawal symptoms when stopping use', null=True),
        ),
    ]
