# Generated by Django 4.2.7 on 2026-04-28 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_druginformation_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitationcenter',
            name='comments',
            field=models.TextField(blank=True, help_text='User comments about the center', null=True),
        ),
        migrations.AddField(
            model_name='rehabilitationcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehabilitationcenter',
            name='user_ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average user rating (0-5)', max_digits=3),
        ),
    ]
