# Generated by Django 4.2.7 on 2026-05-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_conversation_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='core_messag_convers_d2b392_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='core_messag_receive_cf6a82_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='core_messag_sender__43db24_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted_by_receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted_by_sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
